apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
 name: app

resources:
- ./database/replication-controller.yaml
- ./database/service.yaml 
- ./app/replication-controller-orange.yaml
- ./app/service.yaml
